### PR TITLE
switch to using shared lib

### PR DESCRIPTION
**Pull request by kvsikand**
Pull out shared logic for robofleet client into a shared library, which has most of the "interesting" logic, and has no QT/ROS dependencies.

This library is re-used by robofleet_base_client, which is a  ROS-free robofleet client

### CODE REVIEW

**Comment by kvsikand** [comment]
Hoping for thoughts on this change. Basically we move the "logic" and the generated schemas etc. into a shared submodule that is used by both this code and the `robofleet_base_client` code, so that any updates there will be shared

**Comment by loganzartman** [comment]
Haven't had time to review the code in detail, but generally this seems reasonable. Since we're going the route of supporting non-ROS data, you should be sure that the protocol allows clients to clearly distinguish ROS messages from non-ROS messages (using the `type` field in some predictable way, maybe?) It shouldn't blow up if something is expecting a topic to contain ROS messages but someone transmits something else. 

Also, it might be a good idea to go even further and move all of the schema and generated code to its own package that webviz and the ros client can consume, but that's maybe out of scope here.

**Comment by kvsikand** [comment]
> Since we're going the route of supporting non-ROS data, you should be sure that the protocol allows clients to clearly distinguish ROS messages from non-ROS messages (using the `type` field in some predictable way, maybe?) It shouldn't blow up if something is expecting a topic to contain ROS messages but someone transmits something else.

The most common use case is still that *at least one* half of the communication is speaking ROS...just it sometimes is the case that the client on one end doesn't run ROS (current prime example is a Microsoft HoloLens). Therefore that client creates its own C++ structures that look *a lot* like ROS messages, and uses them accordingly.
I don't think we'll get to a point where the things we are trying to send are entirely unrelated to ROS all that soon, but if we *do* get there, we can definitely establish some convention like this

**Comment by kvsikand** [comment]
> Also, it might be a good idea to go even further and move all of the schema and generated code to its own package that webviz and the ros client can consume, but that's maybe out of scope here.

Yeah, I agree with this in concept, but agreed that its out of scope for now. Moar submodules incoming!

**Comment by kvsikand** [comment]
Separately just tested these changes on the Jackal and it seems happy! The one piece of future work I want to do is move rate limiting into `MessageSchedulerLib` so that the robofleet_client is nothing more than wiring of events & control-flow on top of the library, which handles all the scheduling & encoding. But again, this is follow-up work

**Comment by loganzartman** [comment]
Ok, makes sense—you're creating ROS-like data without real ROS messages as the source. I think you can send anything over the wire as long as it extends the base flatbuffer schema with predictable metadata.

**Comment by joydeep-b** [comment]
I don't think we should distinguish between channels originating from ROS or otherwise. ROS is a robot-specific detail, and the level of astraction of robofleet should just be that we have some named channels with specific schemas. A ROS client can convert from that to and from ROS messages, and non-ROS robots can choose to convert to and from whatever format they want. By having it just be a set of named channels on robofleet, ROS robots can communicate with non-ROS agents. A known use case for example is for ROS-enabled robots to send commands to the non-ROS elevator interface, and to be able to see status updates.

**Pull request merged**
